### ISSUE TITLE
browser dead when parse comment string

### ISSUE THREAD

**Issue by ben7th** [cwdoh/cssparser.js#5]
I tried input a comment string like:

```css
/* test */
```

in http://cwdoh.com/cssparser.js/demo/CSS_stringify.html
and press `Transform`

then browser dead. :(

is there endless loop?

**Comment by rkoberg** [comment]
Yes, the parser chokes on comments in CSS:
```
myproject/node_modules/epub/node_modules/xml2js/lib/xml2js.js:216
          throw ex;
                ^
TypeError: Object /* Page Styles */
...snip rest of css..

 has no method 'match'
    at Object.lexer.next myproject/node_modules/cssparser/lib/cssparser.js:788:37)
    at Object.lex (myproject/node_modules/cssparser/lib/cssparser.js:829:22)
    at lex myproject/node_modules/cssparser/lib/cssparser.js:460:28)
    at Object.parse (myproject/node_modules/cssparser/lib/cssparser.js:473:26)
    at EPub.<anonymous> (myproject/tasks/epub.js:44:27)
```
It also chokes on things like:
margin :  2px  ;

It does not support the vh, vw, etc like:
margin:0vh;

**Comment by cwdoh** [comment]
There was a typo which make browser hang on the empty source.
That's fixed by @ijprest. Thanks.
